version: "2"

services:
    containerman:
        container_name: containerman
        image: docker.io/selfhostedpro/yacht:latest
        volumes:
            - /data/yacht:/config
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: host
        environment:
            - ADMIN_EMAIL=lemniskett@mokoupi.local
            - SECRET_KEY=5wdOCblepO

    pihole:
        container_name: pihole
        image: docker.io/pihole/pihole:latest
        volumes:
            - /data/pihole:/etc/pihole
            - /data/dnsmasq.d:/etc/dnsmasq.d
        network_mode: host
        environment:
            - TZ=Asia/Jakarta
        cap_add:
            - NET_ADMIN
