version: "2"

services:
    containerman:
        image: docker.io/selfhostedpro/yacht:latest
        volumes:
            - /data/yacht:/config
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            sub0:
                ipv4_address: 192.168.255.2
        ports:
            - 8000:8000/tcp
        environment:
            - ADMIN_EMAIL=lemniskett@mokoupi.local
            - SECRET_KEY=5wdOCblepO

networks: 
    sub0:
        ipam:
            config:
              - subnet: 192.168.255.0/24
