version: "2"

services:
    nginx:
        image: "192.168.254.3:5000/nginx:latest"
        volumes:
            - /data/webroot:/data/webroot
            - ./custom/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./custom/nginx/nginx.d:/etc/nginx/nginx.d
        networks:
            sub1:
                ipv4_address: 192.168.255.2
        ports:
            - "8080:8080"
            - "8180:8180"
            - "8280:8280"
            - "8380:8380"
            - "8480:8480"

    php-fpm:
        image: "192.168.254.3:5000/php-fpm:latest"
        volumes:
            - /data/webroot:/data/webroot
        networks:
            sub1:
                ipv4_address: 192.168.255.3

    mysql:
        image: "ghcr.io/linuxserver/mariadb:alpine"
        volumes:
            - /data/mysql:/config/databases
        networks:
            sub1:
                ipv4_address: 192.168.255.4
        environment:
            - TZ=Asia/Jakarta
            - MYSQL_ROOT_PASSWORD=root
            - PUID=100
            - PGID=100
    
    postgres:
        image: "docker.io/library/postgres:13"
        volumes:
            - /data/postgres:/var/lib/postgresql/data
        networks:
            sub1:
                ipv4_address: 192.168.255.5
        environment:
            - LC_ALL=en_US.UTF-8
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US.UTF-8
            - POSTGRES_PASSWORD=postgres

    gitea:
        image: "docker.io/kunde21/gitea-arm:latest"
        networks:
            sub1:
                ipv4_address: 192.168.255.6
        volumes:
            - /data/gitea:/data
            - /data/gitea/keys:/data/git/.ssh
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - USER_UID=973
            - USER_GID=973
        ports:
            - "8222:22"

networks: 
    sub1:
        ipam:
            config:
              - subnet: 192.168.255.0/24
