version: "2"

services:
    containerman:
        image: "docker.io/portainer/portainer-ce:alpine"
        volumes:
            - /data/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            sub0:
                ipv4_address: 192.168.254.2
        ports:
            - "9000:9000/tcp"

    registry:
        image: "docker.io/library/registry:latest"
        volumes:
            - /data/registry:/var/lib/registry
        networks:
            sub0:
                ipv4_address: 192.168.254.3

networks: 
    sub0:
        ipam:
            config:
              - subnet: 192.168.254.0/24
